### PR TITLE
Add dependent package

### PR DESCRIPTION
**Pull request by snowsky**

### CODE REVIEW

**Comment by adrianmcli** [comment]
What's the purpose of this PR?

**Comment by snowsky** [comment]
Oh, I use "npm start" but got the error:
``` FAIL  ./test.js
  ● Test suite failed to run

    Cannot find module 'typedarray-to-buffer' from 'W3CWebSocket.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)```

It got fixed after installed the module.

**Comment by adrianmcli** [comment]
It looks to be an issue with NPM not being deterministic: https://stackoverflow.com/questions/50759779/non-deterministic-behavior-of-npm

I was able to reproduce once, but not every time. I'd hesitate to merge this PR as `typedarray-to-buffer` is not an explicit dependency of this project.

**Comment by snowsky** [comment]
ic let me close the issue

**Pull request closed without merging**
